name: doc-scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=20.0
  - requests>=2.25.0
  - beautifulsoup4>=4.9.0
  - pyyaml>=6.0
  - rich>=10.0.0
  - pip:
    - markdownify>=0.11.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - typer>=0.9.0 